// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/src/main/protobuf/webutil/html/types/html.proto
// Protobuf Java Version: 4.28.2

package com.google.common.html.types;

public final class Html {
  private Html() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      Html.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_webutil_html_types_SafeHtmlProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_webutil_html_types_SafeHtmlProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_webutil_html_types_SafeUrlProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_webutil_html_types_SafeUrlProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_webutil_html_types_TrustedResourceUrlProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_webutil_html_types_TrustedResourceUrlProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_webutil_html_types_SafeStyleProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_webutil_html_types_SafeStyleProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_webutil_html_types_SafeScriptProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_webutil_html_types_SafeScriptProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_webutil_html_types_SafeStyleSheetProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_webutil_html_types_SafeStyleSheetProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n5proto/src/main/protobuf/webutil/html/t" +
      "ypes/html.proto\022\022webutil.html.types\"R\n\rS" +
      "afeHtmlProto\022A\n5private_do_not_access_or" +
      "_else_safe_html_wrapped_value\030\002 \001(\tB\002\010\001\"" +
      "L\n\014SafeUrlProto\022<\n4private_do_not_access" +
      "_or_else_safe_url_wrapped_value\030\003 \001(\t\"c\n" +
      "\027TrustedResourceUrlProto\022H\n@private_do_n" +
      "ot_access_or_else_trusted_resource_url_w" +
      "rapped_value\030\004 \001(\t\"P\n\016SafeStyleProto\022>\n6" +
      "private_do_not_access_or_else_safe_style" +
      "_wrapped_value\030\005 \001(\t\"V\n\017SafeScriptProto\022" +
      "C\n7private_do_not_access_or_else_safe_sc" +
      "ript_wrapped_value\030\006 \001(\tB\002\010\001\"_\n\023SafeStyl" +
      "eSheetProto\022H\n<private_do_not_access_or_" +
      "else_safe_style_sheet_wrapped_value\030\007 \001(" +
      "\tB\002\010\001*\344\002\n\023CustomSafeUrlScheme\022\007\n\003TEL\020\000\022\007" +
      "\n\003SMS\020\001\022\n\n\006CALLTO\020\002\022\010\n\004WTAI\020\003\022\010\n\004RTSP\020\004\022" +
      "\n\n\006MARKET\020\005\022\007\n\003GEO\020\006\022\t\n\005SKYPE\020\007\022\014\n\010WHATS" +
      "APP\020\010\022\010\n\004ITMS\020\024\022\016\n\nITMS_BOOKS\020\t\022\t\n\005GLASS" +
      "\020\n\022\r\n\tITMS_APPS\020\013\022\016\n\nITMS_APPSS\020\023\022\021\n\rITM" +
      "S_SERVICES\020\026\022\023\n\017GOOGLEASSISTANT\020\014\022\026\n\022ASS" +
      "ISTANT_SETTINGS\020\r\022\007\n\003SSH\020\016\022\n\n\006INTENT\020\017\022\007" +
      "\n\003SIP\020\020\022\016\n\nGOOGLEHOME\020\021\022\016\n\nCHROMECAST\020\022\022" +
      "\007\n\003PAY\020\025\022\r\n\tGOOGLEAPP\020\027\022\007\n\003CID\020\030\022\n\n\006WEBC" +
      "AL\020\031B&\n\034com.google.common.html.typesB\004Ht" +
      "mlP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_webutil_html_types_SafeHtmlProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_webutil_html_types_SafeHtmlProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_webutil_html_types_SafeHtmlProto_descriptor,
        new java.lang.String[] { "PrivateDoNotAccessOrElseSafeHtmlWrappedValue", });
    internal_static_webutil_html_types_SafeUrlProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_webutil_html_types_SafeUrlProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_webutil_html_types_SafeUrlProto_descriptor,
        new java.lang.String[] { "PrivateDoNotAccessOrElseSafeUrlWrappedValue", });
    internal_static_webutil_html_types_TrustedResourceUrlProto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_webutil_html_types_TrustedResourceUrlProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_webutil_html_types_TrustedResourceUrlProto_descriptor,
        new java.lang.String[] { "PrivateDoNotAccessOrElseTrustedResourceUrlWrappedValue", });
    internal_static_webutil_html_types_SafeStyleProto_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_webutil_html_types_SafeStyleProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_webutil_html_types_SafeStyleProto_descriptor,
        new java.lang.String[] { "PrivateDoNotAccessOrElseSafeStyleWrappedValue", });
    internal_static_webutil_html_types_SafeScriptProto_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_webutil_html_types_SafeScriptProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_webutil_html_types_SafeScriptProto_descriptor,
        new java.lang.String[] { "PrivateDoNotAccessOrElseSafeScriptWrappedValue", });
    internal_static_webutil_html_types_SafeStyleSheetProto_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_webutil_html_types_SafeStyleSheetProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_webutil_html_types_SafeStyleSheetProto_descriptor,
        new java.lang.String[] { "PrivateDoNotAccessOrElseSafeStyleSheetWrappedValue", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
